# Generated by Django 5.1.6 on 2025-03-24 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_feed', '0002_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-publish_time']},
        ),
    ]
