# Generated by Django 5.1.6 on 2025-04-11 05:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_feed', '0004_alter_news_publish_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='publish_time',
            field=models.DateTimeField(verbose_name=django.utils.timezone.now),
        ),
    ]
