# Generated by Django 5.1.6 on 2025-04-11 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_feed', '0005_alter_news_publish_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.CharField(blank=True, max_length=250, unique=True),
        ),
    ]
