# Generated by Django 5.1.6 on 2025-04-28 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_feed', '0009_alter_news_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.CharField(max_length=250),
        ),
    ]
